name: 'run-notebook'
description: 'Run notebook'
author: 'yaananth'
inputs:
  notebook:
    description: 'Path to notebook with extension that should be executed'
    default: ''
  params:
    description: 'Path to parameters file with extension, contents should be json'
    default: '{}'
  isReport:
    description: 'If True, will hide inputs in notebook'
    default: False
  poll:
    description: 'If True, will hide poll for output'
    default: False
branding:
  icon: 'book'
  color: 'orange'
runs:
  using: 'node12'
  main: 'lib/main.js'
